apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: svc-ordersystem-api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ordersystem-nodeapi
  type: LoadBalancer
