apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  labels:
    name: api-configmap
data:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  TOKEN_MERCADO_PAGO: ${{ secrets.TOKEN_MERCADO_PAGO }}
  USERID: ${{ secrets.USERID }}
  POSID: ${{ secrets.POSID }}
  NODE_LOCAL_PORT: ${{ secrets.NODE_LOCAL_PORT }}
