FROM node:20 AS builder

WORKDIR /app

COPY ./backend/package.json ./package.json
COPY ./backend/yarn.lock ./yarn.lock
COPY ./backend/tsconfig.json ./tsconfig.json
COPY ./backend/prisma ./prisma

# Install app dependencies
RUN yarn
# Generate prisma client, leave out if generating in `postinstall` script
RUN yarn generate

COPY . .

RUN yarn build

FROM node:20-buster

ENV DATABASE_URL="uri"
ENV TOKEN_MERCADO_PAGO="uri"
ENV USERID="uri"
ENV POSID="uri"
ENV NODE_LOCAL_PORT="uri"

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD [ "yarn", "start:migrate:prod" ]