version: '3.9'

services:
  app:
    image: node:18-slim
    depends_on:
      - mysql
    ports:
      - 3000:3000
    working_dir: /app
    build:
      context:
      dockerfile: Dockerfile
    volumes:
      - ./:/app

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_DB: mysql

  mysql:
    image: mysql:latest
    volumes:
      - dbMySql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbMySql
