# GET
# Busca pedido
###

GET http://localhost:3000/orders/1
Content-Type: application/json

# POST
# Criar pedido
###

POST http://localhost:3000/orders
Content-Type: application/json

{
  "customerID": 1,
  "amount": 55,
  "orderItens": [
    {
      "name": "Coca-cola",
      "quantity": 10,
      "priceUnit": 5.5,
      "productID": 1,
    }
  ]
}